apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-pqbukjul
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-pqbukjul 
  name: go-pqbukjul
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-pqbukjul
    weight: 100 
